# Generated by Django 4.2.5 on 2023-09-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('price', models.CharField(blank=True, max_length=10)),
                ('rating', models.CharField(blank=True, max_length=4)),
                ('discount', models.CharField(default='No Discount', max_length=11)),
            ],
        ),
    ]
